
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\mpsua\OneDrive\Escritorio\ud\TERCERO\ACO\proyecto\ventana\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

usuario = "ejemplo@gmail.com"
contraseña = "1234"

window = Tk()

window.geometry("552x418")
window.configure(bg = "#FFFFFF")


ventPrinc = Canvas(
    window,
    bg = "#FFFFFF",
    height = 418,
    width = 552,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

ventPrinc.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = ventPrinc.create_image(
    276.0,
    209.0,
    image=image_image_1
)


entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = ventPrinc.create_image(
    111.0,
    366.0,
    image=entry_image_1
)
entryPwd = Text(
    bd=0,
    bg="#9CC1D8",
    fg="#000716",
    highlightthickness=0
)
entryPwd.place(
    x=16.0,
    y=356.0,
    width=190.0,
    height=18.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = ventPrinc.create_image(
    111.0,
    308.0,
    image=entry_image_2
)
entryEmail = Text(
    bd=0,
    bg="#9CC1D8",
    fg="#000716",
    highlightthickness=0
)
entryEmail.place(
    x=16.0,
    y=298.0,
    width=190.0,
    height=18.0
)

ventPrinc.create_text(
    16.0,
    334.0,
    anchor="nw",
    text="Contraseña:",
    fill="#FEFEFE",
    font=("Inter", 12 * -1)
)

ventPrinc.create_text(
    16.0,
    276.0,
    anchor="nw",
    text="Email:",
    fill="#FFFFFF",
    font=("Inter", 12 * -1)
)
window.resizable(False, False)
window.mainloop()


def login(self):
    entryEmail.get()
    entryPwd.get()

